import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Check, Plus, X } from '@phosphor-icons/react';
import { GameCover, GameDetailDialog, GameFilters } from './GamePresentation';
import { matchesGameFilter, type ConsoleId, type Game } from '../lib/rental';
import { useI18n } from '../lib/i18n';

export function GamePicker({ games, consoleId, selected, maxGames, onToggle, onClose }: { games: Game[]; consoleId: ConsoleId; selected: string[]; maxGames: number; onToggle: (id: string) => void; onClose: () => void }) {
  const { t } = useI18n();
  const dialog = useRef<HTMLDialogElement>(null);
  const detailOpener = useRef<HTMLElement | null>(null);
  const [filter, setFilter] = useState('all');
  const [detail, setDetail] = useState<Game | null>(null);
  const [coverWidth, setCoverWidth] = useState(280);
  const visible = games.filter(game => matchesGameFilter(game, consoleId, filter));
  useEffect(() => { dialog.current?.showModal(); return () => dialog.current?.close(); }, []);
  const close = () => { dialog.current?.close(); onClose(); };
  const closeDetail = () => { setDetail(null); requestAnimationFrame(() => detailOpener.current?.focus({ preventScroll: true })); };
  return <><dialog ref={dialog} className="game-picker-dialog" aria-labelledby="game-picker-title" onCancel={event => { event.preventDefault(); close(); }} onClick={event => { if (event.target === event.currentTarget) close(); }}><div className="game-picker-inner"><div className="game-picker-heading"><div><p className="eyebrow">{consoleId.toUpperCase()}</p><h2 id="game-picker-title">{t('Обери бажані ігри.', 'Выбери желаемые игры.')}</h2></div><button type="button" className="icon-button" autoFocus aria-label={t('Закрити добірку ігор', 'Закрыть подборку игр')} onClick={close}><X size={22} /></button></div><GameFilters value={filter} onChange={setFilter} /><div className="game-picker-grid">{visible.map(game => <article className="picker-game" key={game.id}><button type="button" className="game-art" aria-label={`${t('Детальніше про', 'Подробнее об игре')} ${game.title}`} onClick={event => { detailOpener.current = event.currentTarget; setCoverWidth(event.currentTarget.clientWidth); setDetail(game); }}><GameCover game={game} sizes="(max-width: 700px) 40vw, 240px" /><span className="game-open-icon"><ArrowUpRight size={18} /></span></button><h3>{game.title}</h3><button type="button" className={`picker-game-toggle${selected.includes(game.id) ? ' selected' : ''}`} aria-pressed={selected.includes(game.id)} aria-label={`${selected.includes(game.id) ? t('Прибрати із заявки', 'Убрать из заявки') : t('Додати до заявки', 'Добавить в заявку')} ${game.title}`} disabled={!selected.includes(game.id) && selected.length >= maxGames} onClick={() => onToggle(game.id)}>{selected.includes(game.id) ? <Check size={17} /> : <Plus size={17} />}{selected.includes(game.id) ? t('Обрано', 'Выбрано') : t('Додати', 'Добавить')}</button></article>)}</div>{visible.length === 0 && <p className="empty-state">{t('У цій категорії поки немає ігор.', 'В этой категории пока нет игр.')}</p>}{selected.length >= maxGames && maxGames < games.filter(game => game.platforms.includes(consoleId)).length && <p className="input-help" role="status">{t('До заявки можна додати до', 'В заявку можно добавить до')} {maxGames} {t('ігор.', 'игр.')}</p>}<div className="game-picker-footer"><p>{t('Наявність підтвердимо перед орендою.', 'Наличие подтвердим перед арендой.')}</p><button type="button" className="button button-light" onClick={close}>{t('Готово', 'Готово')} <Check size={18} /></button></div></div></dialog>{detail && <GameDetailDialog game={detail} consoleId={consoleId} selected={selected.includes(detail.id)} coverWidth={coverWidth} disabled={!selected.includes(detail.id) && selected.length >= maxGames} disabledMessage={!selected.includes(detail.id) && selected.length >= maxGames ? t('У заявці вже максимум ігор. Прибери іншу, щоб додати цю.', 'В заявке уже максимум игр. Убери другую, чтобы добавить эту.') : undefined} onToggle={() => onToggle(detail.id)} onClose={closeDetail} />}</>;
}
