import { ArrowUpRight, PlugsConnected, GameController, Plug, BookOpen, Disc, Truck, MapPin, ArrowRight } from '@phosphor-icons/react';
import { Reveal } from '../../components/ui/reveal';
import ScrollRevealImage from '../../components/ui/scroll-reveal-image';
import { imageUrl, type StoreSettings } from '../lib/api';

export function Experience() {
  return <section className="experience-section" aria-label="Досвід PlayStation"><div className="shell"><Reveal className="experience-heading"><p className="eyebrow">УВІМКНИ. ВІДЧУЙ. ГРАЙ.</p><h2>Більше, ніж<br />просто вечір.</h2><p>Ще один матч. Ще одна пригода.<br />Ще одна причина зібратися разом.</p></Reveal></div><ScrollRevealImage className="experience-photo" src={imageUrl('dualsense-detail')} alt="Крупний план білого DualSense з деталями кнопок та фактури" /><div className="shell experience-caption"><span>DUALSENSE / ВІДЧУЙ КОЖЕН МОМЕНТ</span><a className="text-link" href="#booking">Зробити свій план <ArrowUpRight size={17} /></a></div></section>;
}
export function InTheBox() {
  const items = [[GameController, 'Консоль і геймпад', 'PS5 або PS4 — твій вибір'], [PlugsConnected, 'HDMI-кабель', 'Для підключення до екрана'], [Plug, 'Живлення та зарядка', 'Необхідні кабелі в комплекті'], [Disc, 'Ігри під твій настрій', 'Обрані ігри узгодимо'], [BookOpen, 'Проста інструкція', 'Щоб швидко почати гру'] ] as const;
  return <section className="section box-section" id="kit"><div className="shell"><Reveal className="section-heading"><div><p className="eyebrow">ПРОДУМАНО ДО ДРІБНИЦЬ</p><h2>Від коробки<br />до першої гри.</h2></div><p className="heading-side-copy">Консоль, кабелі й просте підключення.<br />Точний склад узгодимо перед орендою.</p></Reveal><div className="kit-grid">{items.map(([Icon, title, description], index) => <Reveal delay={index * 0.05} key={title} className="kit-item"><Icon size={34} weight="light" /><h3>{title}</h3><p>{description}</p></Reveal>)}</div></div></section>;
}
export function HowItWorks() {
  const steps = [['Обирай комплект', 'PS5 або PS4. Один геймпад чи два.'], ['Плануй свій час', 'Обери термін і дату отримання.'], ['Отримуй консоль', 'Узгодимо доставку та підключення.'], ['Насолоджуйся грою', 'Відкривай нові світи вдома.'], ['Повертай без клопоту', 'Узгодимо час і спосіб повернення.']];
  return <section className="section how-section" id="how-it-works"><div className="shell"><Reveal className="section-heading"><div><p className="eyebrow">П’ЯТЬ ПРОСТИХ КРОКІВ</p><h2>Менше клопоту.<br />Більше гри.</h2></div><p className="heading-side-copy">Від вибору консолі до останнього рівня.<br />Усе зрозуміло з першого кроку.</p></Reveal><div className="steps-grid">{steps.map(([title, description], index) => <Reveal key={title} delay={index * 0.06} className="step"><span className="step-number">0{index + 1}</span><h3>{title}</h3><p>{description}</p>{index < 4 && <ArrowRight className="step-arrow" size={19} />}</Reveal>)}</div></div></section>;
}
export function Delivery({ settings }: { settings: StoreSettings }) {
  return <section className="section delivery-section" id="delivery"><div className="shell delivery-layout"><Reveal><p className="eyebrow">ПРИВЕЗЕМО ГРУ ДО ТЕБЕ</p><h2>Твій дім —<br />місце подій.</h2><p className="delivery-intro">{settings.deliveryText}</p><a href="#booking" className="button button-outline">Вказати адресу <ArrowUpRight size={18} /></a></Reveal><Reveal className="delivery-details"><div><MapPin size={25} weight="light" /><h3>{settings.city ? `Доставка: ${settings.city}` : 'Доставка за твоєю адресою'}</h3><p>{settings.city ? 'Вкажи адресу — перевіримо зону сервісу та узгодимо час.' : 'Місто, район і зручний час перевіримо після заявки.'}</p></div><div><Truck size={25} weight="light" /><h3>Від {settings.freeDeliveryFrom} днів — без доплат</h3><p>Доставка та підключення безкоштовні в зоні сервісу. Для коротших термінів вартість залежить від адреси.</p></div><div><GameController size={25} weight="light" /><h3>Від підключення до повернення</h3><p>Узгодимо всі деталі до підтвердження. Самовивіз — {settings.pickup ? 'доступний за домовленістю.' : 'можливість уточнюємо.'}</p></div></Reveal></div></section>;
}
