<?php
// Disposable local WordPress only. All mail is intercepted; fixture mutations are restored.
require '/var/www/html/wp-load.php';
$checks=0;$failures=[];$mail=[];$mail_ok=true;
add_filter('pre_wp_mail',function($return,$atts)use(&$mail,&$mail_ok){$mail[]=$atts;return $mail_ok;},10,2);
function backend_check(bool $value,string $label): void { global $checks,$failures;$checks++;if (!$value) $failures[]=$label; }
function backend_game(string $key): WP_Post { $posts=get_posts(['post_type'=>'joyrent_game','post_status'=>array_values(get_post_stati()),'numberposts'=>1,'meta_key'=>'_jr_game_id','meta_value'=>$key,'orderby'=>'ID','order'=>'ASC']);if (!$posts) throw new RuntimeException('Missing game '.$key);return $posts[0]; }
$today=(new DateTimeImmutable('now',new DateTimeZone('Europe/Kyiv')))->format('Y-m-d');
$payload=['console'=>'ps5','days'=>3,'startDate'=>$today,'controllers'=>1,'gameIds'=>[],'name'=>'Локальна перевірка','phone'=>'+380000000001','method'=>'delivery','address'=>'Тестове місто, тестова адреса 1','consent'=>true];
$settings=get_option('joyrent_settings');$version=get_option('joyrent_version');$woo_email=get_option('woocommerce_new_order_settings');$privacy=get_option('wp_page_for_privacy_policy');$query=$GLOBALS['wp_query'];$created=[];$orders=[];$originals=[];$tariff=JR_Store::product('ps4',30);$tariff_status=$tariff->get_status();
foreach (['cod-bo7','gt7','astro-bot'] as $id) { $p=backend_game($id);$originals[$id]=['post'=>$p,'meta'=>get_post_meta($p->ID,'_jr_game',true)]; }
try {
    $inventory=JR_Games::records();$ids=array_values(array_map(fn($g)=>$g['id'],array_filter($inventory,fn($g)=>in_array('ps5',$g['platforms'],true))));
    foreach ([0,1,12,13,count($ids)] as $size) {
        try { $d=JR_Domain::validate(array_merge($payload,['gameIds'=>array_slice($ids,0,$size)]),$today,$inventory);backend_check(count($d['gameIds'])===$size,'Game selection '.$size.' accepted'); }
        catch (InvalidArgumentException $e) { backend_check(false,'Game selection '.$size.' accepted: '.$e->getMessage()); }
    }
    $d=JR_Domain::validate(array_merge($payload,['gameIds'=>[$ids[0],$ids[0]]]),$today,$inventory);backend_check(count($d['gameIds'])===1,'Repeated game IDs normalized');
    foreach ([['gameIds'=>['unknown']],['console'=>'ps4','gameIds'=>['spider-man-2']]] as $changes) { try { JR_Domain::validate(array_merge($payload,$changes),$today,$inventory);backend_check(false,'Invalid game rejected'); } catch (InvalidArgumentException $e) {backend_check(true,'Invalid game rejected');} }
    update_option('joyrent_settings',array_merge(JR_Settings::get(),['max_games'=>2,'email'=>'','notification_email'=>'shop@example.test','delivery_fee'=>'']));
    try { JR_Domain::validate(array_merge($payload,['gameIds'=>array_slice($ids,0,3)]),$today,$inventory);backend_check(false,'Configured game limit enforced'); } catch (InvalidArgumentException $e) {backend_check(true,'Configured game limit enforced');}
    backend_check((JR_Settings::public()['maxGames']??null)===2,'Configured limit published');
    backend_check(!array_key_exists('notification_email',JR_Settings::public())&&!str_contains(wp_json_encode(JR_Store::catalog()),'shop@example.test'),'Private notification recipient excluded from public catalog');
    $all_unpublished=function($status,$product){return str_starts_with($product->get_sku(),'joyrent-')?'draft':$status;};add_filter('woocommerce_product_get_status',$all_unpublished,10,2);$none=JR_Store::catalog();backend_check($none['acceptingRequests']===false&&$none['tariffs']['ps5']===[]&&$none['tariffs']['ps4']===[],'No published offers disables requests with empty tariff arrays');remove_filter('woocommerce_product_get_status',$all_unpublished,10);
    $tariff->set_status('draft');$tariff->save();$c=JR_Store::catalog();backend_check($c['acceptingRequests']===true,'One hidden tariff leaves other offers accepting requests');backend_check(!in_array(30,array_column($c['tariffs']['ps4'],'days'),true),'Hidden tariff omitted');$tariff->set_status($tariff_status);$tariff->save();
    update_option('joyrent_settings',array_merge(JR_Settings::get(),['max_games'=>100,'email'=>'','notification_email'=>'shop@example.test','delivery_fee'=>'']));
    foreach ([3=>'pending',7=>'pending',30=>'pending'] as $days=>$delivery) {
        $d=JR_Domain::validate(array_merge($payload,['days'=>$days]),$today,$inventory);$d['language']='uk';$key=hash('sha256',wp_generate_uuid4());$receipt=JR_Orders::create($d,$key,hash('sha256',wp_json_encode($d)));$order=wc_get_order((int)substr($receipt['reference'],3));$orders[]=$order->get_id();backend_check($order->get_meta('_joyrent_delivery')===$delivery,'Delivery '.$days.' days awaits address and zone confirmation');
    }
    backend_check(count($mail)===3,'One shop notification per completed request');backend_check(isset($mail[0])&&$mail[0]['to']==='shop@example.test','Configured shop recipient used');
    if (method_exists('JR_Orders','notify')) {
        $order=wc_get_order($orders[0]);JR_Orders::notify($order->get_id());backend_check(count($mail)===3,'Successful notification is idempotent');
        $mail_ok=false;$d=JR_Domain::validate($payload,$today,$inventory);$d['language']='ru';$key=hash('sha256',wp_generate_uuid4());$receipt=JR_Orders::create($d,$key,hash('sha256',wp_json_encode($d)));$failed=wc_get_order((int)substr($receipt['reference'],3));$orders[]=$failed->get_id();backend_check($failed->get_meta('_joyrent_notification_status')==='failed','Failed delivery recorded without rejecting saved request');
        $admin=get_users(['role'=>'administrator','number'=>1])[0];wp_set_current_user($admin->ID);ob_start();JR_Orders::notification_admin($failed);$ui=ob_get_clean();backend_check(str_contains($ui,'joyrent_notification_retry')&&str_contains($ui,'Помилка'),'Failed notification and nonce retry visible to order administrator');
        $mail_ok=true;JR_Orders::notify($failed->get_id());$failed=wc_get_order($failed->get_id());backend_check($failed->get_meta('_joyrent_notification_status')==='sent','Failed notification retry succeeds');JR_Orders::notify($failed->get_id());backend_check(count($mail)===5,'Retry does not duplicate order or successful email');
        ob_start();JR_Orders::notification_admin($failed);$ui=ob_get_clean();backend_check(!str_contains($ui,'joyrent_notification_retry'),'Sent notification offers no resend action');
        $failed->update_meta_data('_joyrent_notification_status','sending');$failed->save();JR_Orders::notify($failed->get_id());backend_check(count($mail)===5,'Uncertain interrupted send requires explicit reviewed admin retry');$failed->update_meta_data('_joyrent_notification_status','sent');$failed->save();
    } else backend_check(false,'Failed notification retry exists');
    update_option('joyrent_settings',array_merge(JR_Settings::get(),['email'=>'public-shop@example.test','notification_email'=>'']));backend_check(JR_Orders::notification_recipient()==='public-shop@example.test','Shop email fallback');update_option('joyrent_settings',array_merge(JR_Settings::get(),['email'=>'']));update_option('woocommerce_new_order_settings',['recipient'=>'woo@example.test']);backend_check(JR_Orders::notification_recipient()==='woo@example.test','Woo configured new-order recipient fallback');update_option('woocommerce_new_order_settings',['recipient'=>'']);backend_check(JR_Orders::notification_recipient()===get_option('admin_email'),'WP administrator fallback');
    update_option('joyrent_settings',array_merge(JR_Settings::get(),['notification_email'=>'shop@example.test','base_controllers'=>2,'extra_controller_fee'=>0]));
    foreach ([1,2] as $controllers) {$d=JR_Domain::validate(array_merge($payload,['controllers'=>$controllers]),$today,$inventory);$d['language']='uk';$key=hash('sha256',wp_generate_uuid4());$receipt=JR_Orders::create($d,$key,hash('sha256',wp_json_encode($d)));$order=wc_get_order((int)substr($receipt['reference'],3));$orders[]=$order->get_id();backend_check((int)$order->get_meta('_joyrent_controllers')===$controllers&&(float)$order->get_meta('_joyrent_extra_controller')===0.0,'Included controllers permit request '.$controllers.' without extra fee');}
    $fake_inventory=[];for($i=0;$i<101;$i++)$fake_inventory[]=['id'=>'fixture-'.$i,'platforms'=>['ps5']];
    try {JR_Domain::validate(array_merge($payload,['gameIds'=>array_column($fake_inventory,'id')]),$today,$fake_inventory);backend_check(false,'Sane maximum of 100 unique games enforced');}catch(InvalidArgumentException $e){backend_check(true,'Sane maximum of 100 unique games enforced');}
    $_SERVER['REMOTE_ADDR']='127.0.0.232';$request_id=wp_generate_uuid4();$rest_payload=array_merge($payload,['requestId'=>$request_id,'gameIds'=>array_slice($ids,0,13)]);$rest_request=new WP_REST_Request('POST','/joyrent/v1/requests');$rest_request->set_header('content-type','application/json');$rest_request->set_body(wp_json_encode($rest_payload));$response=JR_REST::create($rest_request);
    backend_check(!is_wp_error($response)&&$response->get_status()===201,'REST accepts 13 published compatible games');
    if(!is_wp_error($response)){$orders[]=(int)substr($response->get_data()['reference'],3);$replay=JR_REST::create($rest_request);backend_check(!is_wp_error($replay)&&$replay->get_status()===200&&$replay->get_data()===$response->get_data(),'REST replay returns original receipt without second order or email');}
    $lock=JR_Lock::acquire('joyrent_catalog_lock');backend_check($lock!==false&&JR_Lock::acquire('joyrent_catalog_lock')===false,'Migration mutex rejects second owner');update_option('joyrent_version','1.5.0');JR_Store::upgrade();backend_check(get_option('joyrent_version')==='1.5.0','Busy migration does not falsely advance version');JR_Lock::release('joyrent_catalog_lock','wrong-owner');backend_check(JR_Lock::acquire('joyrent_catalog_lock')===false,'Mutex cannot be released by different worker');JR_Lock::release('joyrent_catalog_lock',$lock);
    $original=$originals['astro-bot']['post'];$meta=$originals['astro-bot']['meta'];
    $duplicate=wp_insert_post(['post_type'=>'joyrent_game','post_status'=>$original->post_status,'post_title'=>$original->post_title,'post_content'=>$original->post_content,'menu_order'=>$original->menu_order]);$created[]=$duplicate;update_post_meta($duplicate,'_jr_game_id','astro-bot');update_post_meta($duplicate,'_jr_game',$meta);
    backend_check(count(array_filter(JR_Games::records(),fn($g)=>$g['id']==='astro-bot'))===1,'Public game IDs stay unique before migration');
    $owner=wp_insert_post(['post_type'=>'joyrent_game','post_status'=>'publish','post_title'=>'Owner duplicate title','post_content'=>'Owner duplicate description','menu_order'=>$original->menu_order]);$created[]=$owner;update_post_meta($owner,'_jr_game_id','astro-bot');update_post_meta($owner,'_jr_game',$meta);update_post_meta($owner,'_thumbnail_id',12345);
    wp_update_post(['ID'=>$originals['cod-bo7']['post']->ID,'post_content'=>'Owner BO7 description']);$bo=$originals['cod-bo7']['meta'];$bo['descriptionRu']='Owner BO7 RU';$bo['image']='owner-bo7';update_post_meta($originals['cod-bo7']['post']->ID,'_jr_game',$bo);
    update_option('joyrent_version','1.5.0');JR_Store::upgrade();
    backend_check(get_post($duplicate)===null,'Redundant identical managed duplicate removed');backend_check(get_post($owner)!==null&&get_post($owner)->post_content==='Owner duplicate description'&&get_post_meta($owner,'_thumbnail_id',true)==12345,'Owner duplicate edits and thumbnail preserved');
    $records=JR_Games::records();backend_check(count($records)===count(array_unique(array_column($records,'id'))),'Unique IDs after reconciliation');
    $games=array_column($records,null,'id');backend_check(($games['cod-bo7']['playersByPlatform']??[])===['ps5'=>2,'ps4'=>1],'BO7 platform players');backend_check(($games['gt7']['playersByPlatform']??[])===['ps5'=>4,'ps4'=>2],'GT7 platform players');backend_check(($games['cod-bo7']['requiresInternet']??false)===true,'BO7 internet requirement explicit');backend_check($games['cod-bo7']['description']==='Owner BO7 description'&&$games['cod-bo7']['descriptionRu']==='Owner BO7 RU'&&$games['cod-bo7']['image']==='owner-bo7','Fact migration preserves owner copy and image');
    $before=array_map(fn($g)=>$g['id'],$records);JR_Store::upgrade();backend_check($before===array_map(fn($g)=>$g['id'],JR_Games::records()),'Repeated migration is idempotent');
    $draft=wp_insert_post(['post_type'=>'page','post_status'=>'draft','post_title'=>'Draft policy']);$created[]=$draft;update_option('wp_page_for_privacy_policy',$draft);backend_check(function_exists('joyrent_privacy_url')&&str_contains(joyrent_privacy_url(),'konfidentsiinist'),'Published UA privacy fallback replaces draft option');
    $custom=wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>'Owner policy']);$created[]=$custom;update_option('wp_page_for_privacy_policy',$custom);backend_check(joyrent_privacy_url()===get_permalink($custom),'Published assigned owner policy preserved');update_option('wp_page_for_privacy_policy',$privacy);
    $GLOBALS['wp_query']=new WP_Query(['pagename'=>'umovy-orendy']);backend_check(apply_filters('language_attributes','lang="en-US"')==='lang="uk" dir="ltr"','UA legal route has explicit language');
    $GLOBALS['wp_query']=new WP_Query(['pagename'=>'konfidentsialnost']);backend_check(apply_filters('language_attributes','lang="en-US"')==='lang="ru" dir="ltr"','RU legal route has explicit language');
} finally {
    foreach ($orders as $id) { $o=wc_get_order($id);if($o)$o->delete(true); }
    if(isset($request_id))delete_option('jr_result_'.hash_hmac('sha256',$request_id,wp_salt('nonce')));delete_transient('jr_rate_'.hash_hmac('sha256','127.0.0.232',wp_salt('auth')));
    foreach ($created as $id) if (get_post($id)) wp_delete_post($id,true);
    foreach ($originals as $value) { $p=$value['post'];wp_update_post(['ID'=>$p->ID,'post_title'=>$p->post_title,'post_content'=>$p->post_content,'menu_order'=>$p->menu_order,'post_status'=>$p->post_status]);update_post_meta($p->ID,'_jr_game',$value['meta']); }
    $tariff->set_status($tariff_status);$tariff->save();update_option('joyrent_settings',$settings);update_option('joyrent_version',$version);update_option('woocommerce_new_order_settings',$woo_email);update_option('wp_page_for_privacy_policy',$privacy);$GLOBALS['wp_query']=$query;
}
echo wp_json_encode(['checks'=>$checks,'failures'=>$failures,'mailAttempts'=>count($mail)],JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT)."\n";
exit($failures?1:0);
